apiVersion: v1
kind: Pod
metadata:
  namespace: my-app
  name: my-app
  labels:
    aadpodidbinding: crgar-aks-msi-aks-pod-identity
spec:
  containers:
  - name: my-app
    image: ubuntu
    stdin: true 
    tty: true     
    command:
      - /bin/bash
    env:
      - name: MY_POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: MY_POD_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: MY_POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
  nodeSelector:
    kubernetes.io/os: linux